import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Open_Sans, Playfair_Display, Montserrat } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
  display: "swap",
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  display: "swap",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${openSans.variable} ${playfairDisplay.variable} ${montserrat.variable}`}
    >
      <body
        className={`min-h-screen  bg-background-primary text-text-primary ${openSans.className}>`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
